config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms do
    resources :posts do
      collection do
        get 'ongoing_index'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  before_create :set_posted_at
  validates :title, :content, presence: true
  belongs_to :user
  belongs_to :room

  private

  def set_posted_at
    date = Time.now
    year = date.year
    month = date.month
    day = date.day
    self.posted_at = "#{year}-#{month}-#{day}"
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :posts, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :room_users
  has_many :rooms, through: :room_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_room
  before_action :set_post, only: [:update, :destroy]
  before_action :authenticate_user!

  def index
    # @posts = Post.where(params[:room_id]).order(created_at: :desc)
    @rooms = Room.all
    @post = Post.new
    @posts = @room.posts.includes(:user).order(created_at: :desc)
  end
  
  def create
    @posts = Post.all.order(created_at: :desc)
    @rooms = Room.all
    # @post = @room.posts.build(post_params)
    post = @room.posts.create(post_params)
    # if @post.save
    #   redirect_to room_posts_path(@room)
    # else
    #   render :index, status: :unprocessable_entity
    # end
    # post = Post.create(post_params)
    render json:{ post: post }
  end
  
  def update
    @post.update(post_params)
    render json:{ post: @post }
  end

  def destroy
    @post.destroy
    head :no_content
  end

  def ongoing_index
    @posts = Post.where(status: '継続').order(created_at: :desc)
    respond_to do |format|
      format.html
      format.json { render json: @posts.map { |post| { id: post.id, posted_at: post.posted_at, title: post.title, pic: post.pic, status: post.status, content: post.content, created_at: post.created_at, updated_at: post.updated_at } } }
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :pic, :status, :content).merge(user_id: current_user.id)
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:destroy]
  before_action :authenticate_user!

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_posts_path(@room)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy
    head :no_content
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KKApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header class="bg-cyan-800 p-4 text-white">
      <nav class="flex-col sm:flex-row flex justify-between mx-auto container items-center">
        <div class="my-4 sm:my-0 text-4xl">課題管理表</div>
        <div class="space-x-4 font-bold">
          <% if user_signed_in? %>
            <a href="/" class="hover:text-green-200 transition-all duration-300">プロジェクト一覧</a>
            <%= link_to "ログアウト", destroy_user_session_path, class: "hover:text-green-200 transition-all duration-300", data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "hover:text-green-200 transition-all duration-300" %>
            <%= link_to "新規登録", new_user_registration_path, class: "hover:text-green-200 transition-all duration-300" %>
          <% end %>
        </div>
      </nav>
    </header>
    <main class="container mx-auto mt-5 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<%= form_with url: '', method: :get, id: 'room-select-form', class: 'px-3', local: true do %>
  <div class="text-2xl block py-2">プロジェクト</div>
  <div class="lg:flex items-center">
    <select id="room-select"  class="w-full lg:w-7/12">
      <optgroup label=""></optgroup>
      <option value=""><%= @room.name %></option>
      <% @rooms.each do |room| %>
        <% next if room == @room %> <!-- 現在の @room をスキップ -->
        <option value="<%= room.id %>"><%= room.name %></option>
      <% end %>
    </select>
    <div class="flex lg:px-3">
      <%= link_to "プロジェクト追加", new_room_path, class: "text-sm lg:text-base block my-2 px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300" %>
      <button id="delete-room" class="text-sm lg:text-base block mx-3 my-2 px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-red-700 cursor-pointer transition-all duration-300" data-room-id="<%= @room.id %>">プロジェクト削除</button>
    </div>
  </div>
  <!-- /.lg:flex -->
<% end %>
<%= form_with model: [@room, @post], data: { room_id: @room.id }, method: :post, id: "form", remote: true do |form| %>
  <div class="lg:flex justify-left flex-wrap">
    <div class="py-4 basis-1/3 px-3">
      <%= form.label "title", "タイトル", class: "text-2xl block py-2" %>
      <%= form.text_field "title", id: "title", class: "w-full" %>
    </div>
    <div class="py-4 px-3">
      <%= form.label "pic", "担当者", class: "text-2xl block py-2" %>
      <%= form.text_field "pic", value: current_user.nickname, readonly: true, id: "pic", class: "w-full" %>
    </div>
    <div class="py-4 px-3">
      <%= form.label "status", "ステータス", class: "text-2xl block py-2" %>
      <%= form.select "status", [["継続", "継続"], ["解決", "解決"], ["記録のみ", "記録のみ"]], selected: "記録のみ", id: "status", class: "w-full" %>
    </div>
    <div class="py-4 basis-full px-3">
      <%= form.label "content", "詳細", class: "text-2xl block py-2" %>
      <%= form.text_area "content", rows: 7, id: "content", class: "w-full" %>
    </div>
  </div>
  <div class="flex justify-end px-3 pb-4">
    <%= form.submit '投稿する', id: "submit", class:"block px-6 py-3 bg-blue-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300" %>
  </div>
<% end %>
<hr>
<button id="ongoing-button" class="block px-6 py-3 my-4 bg-blue-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300" data-room-id="<%= @room.id %>">継続を表示</button>
<div id="list">
</div>
<% @posts.each do |post| %>
  <div class="post bg-amber-100 shadow-xl rounded-md px-3 py-3 my-7" id="post-<%= post.id %>" data-post-id="<%= post.id %>">
    <div class="flex justify-between md:text-lg">
      <div>
        No. <span class="post-id"><%= post.id %></span><!-- /.post-id -->
      </div>
      <div>
        記入日：<span class="posted-at"><%= post.posted_at %></span><!-- /.posted-at -->
      </div>
    </div>
    <div class="text-2xl md:text-3xl">
      「<span class="post-title"><%= post.title %></span><!-- /.post-title -->」
    </div>
    <div class="flex justify-between md:text-lg">
      <div>
        担当者：<span class="post-pic"><%= post.pic %></span><!-- /.post-pic -->
      </div>
      <div>
        ステータス：<span class="post-status"><%= post.status %></span><!-- /.post-status -->
      </div>
    </div>
    <div class="text-lg py-1 md:text-2xl">
      <span class="post-content"><%= post.content %></span><!-- /.post-content -->
    </div>
    <div class="flex justify-end">
      <button class="edit-button block mx-3 px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-green-700 cursor-pointer transition-all duration-300" data-room-id="<%= @room.id %>" data-post-id="<%= post.id %>">編集</button>
      <button class="delete-button block px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-red-700 cursor-pointer transition-all duration-300" data-room-id="<%= @room.id %>" data-post-id="<%= post.id %>">削除</button>
    </div>
  </div>
<% end %>
<div class="modal-window-shadow">
  <div class="modal-window-edit container w-full bg-amber-100 shadow-xl rounded-md px-3 py-3 my-7">
    <%= form_with model: [@room, @post], data: { room_id: @room.id }, method: :patch, id: "edit-form", remote: true do |form| %>
      <div class="lg:flex justify-left flex-wrap">
        <div class="py-4 basis-1/3 px-3">
          <%= form.label "title", "タイトル", class: "text-2xl block py-2" %>
          <%= form.text_field "title", value: "rtwe", id: "edit-title", class: "w-full" %>
        </div>
        <div class="py-4 px-3">
          <%= form.label "pic", "担当者", class: "text-2xl block py-2" %>
          <%= form.text_field "pic", value: current_user.nickname, readonly: true, id: "edit-pic", class: "w-full" %>
        </div>
        <div class="py-4 px-3">
          <%= form.label "status", "ステータス", class: "text-2xl block py-2" %>
          <%= select_tag "post[status]", options_for_select([["継続", "継続"], ["解決", "解決"], ["記録のみ", "記録のみ"]]), id: "edit-status", class: "w-full" %>
        </div>
        <div class="py-4 basis-full px-3">
          <%= form.label "content", "詳細", class: "text-2xl block py-2" %>
          <%= form.text_area "content", value: "aaaa", rows: 7, id: "edit-content", class: "w-full" %>
        </div>
      </div>
      <div class="flex justify-end px-3 pb-4">
        <%= form.submit '保存する', id: "edit-submit", class:"block mx-3 px-3 py-3 bg-blue-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300" %>
        <button id="close-modal" class="block px-3 py-3 bg-blue-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300">閉じる</button>
      </div>
    <% end %>
  </div><!-- /.modal-window-edit -->
</div><!-- /.modal-window-shadow -->

app/views/rooms/index.html.erb
<%= form_with url: '', method: :get, id: 'room-select-form', class: 'px-3', local: true do %>
  <div class="text-2xl block py-2">プロジェクト</div>
  <select id="room-select" class="w-full">
    <optgroup label=""></optgroup>
    <option value="">プロジェクトを選択</option>
    <% @rooms.each do |room| %>
      <option value="<%= room.id %>"><%= room.name %></option>
    <% end %>
  </select>
<% end %>
<div class="flex py-3">
  <%= link_to "プロジェクト追加", new_room_path, class: "block mx-3 px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300" %>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form px-3'>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :新規プロジェクト, class: 'chat-room-form__label text-2xl block py-2'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input w-full lg:w-1/2', placeholder: 'プロジェクト名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <!--
        <div class='chat-room-form__field--left'>
          <label class='chat-room-form__label' for='chat_room_チャットメンバー'>プロジェクトメンバー</label>
        </div>
        <div class='chat-room-form__field--right'>
          <select name="room[user_ids][]">
            <option>参加ユーザーを選択してください</option>
            <% User.where.not(id: current_user.id).each do |user| %>
              <option value=<%= user.id %>><%= user.nickname %></option>
            <% end %>
          </select>
          <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
        </div>
      -->
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right flex py-3'>
        <%= f.submit "作成する", class: 'chat-room-form__action-btn block px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300'%>
        <%= link_to "プロジェクト一覧", rooms_path, class: "block mx-3 px-3 py-2 bg-gray-300 rounded-md text-white hover:bg-blue-700 cursor-pointer transition-all duration-300" %>
      </div>
    </div>
  <% end %>
</div>